name: cln_arch_demo
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.11.0







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  dio: ^5.9.1
  retrofit: ^4.9.2
  flutter_riverpod: ^3.2.1
  fpdart: ^1.2.0
  hive_ce_flutter: ^2.3.4
  hive_ce: ^2.19.3
  path_provider: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  build_runner: ^2.11.1
  retrofit_generator: ^10.0.1
  hive_ce_generator: ^1.11.1







flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
